# Dependencies
highlighter:      rouge

# Config
gems: [jekyll-gist,jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Thoughts 'n' such
tagline:          'Summer quarter 2016'
description:      'Steven Porter fiddles his way through Digital Frameworks class.'
url:              http://digitalframeworks.github.io
baseurl:          /

author:
  name:           'Steven Porter'
  url:            https://twitter.com/reporterporter

paginate:         15

exclude: [node_modules]

sass:
  sass_dir: _sass
  style: compressed

# Custom vars
navlinks:
- url: https://nwudigitalframeworks.slack.com/messages/general/
  title: Slack
- url: mailto:davideads@gmail.com
  title: Email
